// Code generated by singee-gen-pp. DO NOT EDIT.

package pp

func RedString(format string, a ...interface{}) String {
	return colorString(RED, format, a...)
}

func RedPrint(a ...interface{}) {
	_ = Stdout.Print(RED, a...)
}

func RedPrintf(format string, a ...interface{}) {
	_ = Stdout.printf(RED, format, a...)
}

func RedPrintln(a ...interface{}) {
	_ = Stdout.Println(RED, a...)
}

func ERedPrint(a ...interface{}) {
	_ = Stderr.Print(RED, a...)
}

func ERedPrintf(format string, a ...interface{}) {
	_ = Stderr.printf(RED, format, a...)
}

func ERedPrintln(a ...interface{}) {
	_ = Stderr.Println(RED, a...)
}

func GreenString(format string, a ...interface{}) String {
	return colorString(GREEN, format, a...)
}

func GreenPrint(a ...interface{}) {
	_ = Stdout.Print(GREEN, a...)
}

func GreenPrintf(format string, a ...interface{}) {
	_ = Stdout.printf(GREEN, format, a...)
}

func GreenPrintln(a ...interface{}) {
	_ = Stdout.Println(GREEN, a...)
}

func EGreenPrint(a ...interface{}) {
	_ = Stderr.Print(GREEN, a...)
}

func EGreenPrintf(format string, a ...interface{}) {
	_ = Stderr.printf(GREEN, format, a...)
}

func EGreenPrintln(a ...interface{}) {
	_ = Stderr.Println(GREEN, a...)
}

func BlueString(format string, a ...interface{}) String {
	return colorString(BLUE, format, a...)
}

func BluePrint(a ...interface{}) {
	_ = Stdout.Print(BLUE, a...)
}

func BluePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(BLUE, format, a...)
}

func BluePrintln(a ...interface{}) {
	_ = Stdout.Println(BLUE, a...)
}

func EBluePrint(a ...interface{}) {
	_ = Stderr.Print(BLUE, a...)
}

func EBluePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(BLUE, format, a...)
}

func EBluePrintln(a ...interface{}) {
	_ = Stderr.Println(BLUE, a...)
}

func CyanString(format string, a ...interface{}) String {
	return colorString(CYAN, format, a...)
}

func CyanPrint(a ...interface{}) {
	_ = Stdout.Print(CYAN, a...)
}

func CyanPrintf(format string, a ...interface{}) {
	_ = Stdout.printf(CYAN, format, a...)
}

func CyanPrintln(a ...interface{}) {
	_ = Stdout.Println(CYAN, a...)
}

func ECyanPrint(a ...interface{}) {
	_ = Stderr.Print(CYAN, a...)
}

func ECyanPrintf(format string, a ...interface{}) {
	_ = Stderr.printf(CYAN, format, a...)
}

func ECyanPrintln(a ...interface{}) {
	_ = Stderr.Println(CYAN, a...)
}

func YellowString(format string, a ...interface{}) String {
	return colorString(YELLOW, format, a...)
}

func YellowPrint(a ...interface{}) {
	_ = Stdout.Print(YELLOW, a...)
}

func YellowPrintf(format string, a ...interface{}) {
	_ = Stdout.printf(YELLOW, format, a...)
}

func YellowPrintln(a ...interface{}) {
	_ = Stdout.Println(YELLOW, a...)
}

func EYellowPrint(a ...interface{}) {
	_ = Stderr.Print(YELLOW, a...)
}

func EYellowPrintf(format string, a ...interface{}) {
	_ = Stderr.printf(YELLOW, format, a...)
}

func EYellowPrintln(a ...interface{}) {
	_ = Stderr.Println(YELLOW, a...)
}

func BoldString(format string, a ...interface{}) String {
	return colorString(BOLD, format, a...)
}

func BoldPrint(a ...interface{}) {
	_ = Stdout.Print(BOLD, a...)
}

func BoldPrintf(format string, a ...interface{}) {
	_ = Stdout.printf(BOLD, format, a...)
}

func BoldPrintln(a ...interface{}) {
	_ = Stdout.Println(BOLD, a...)
}

func EBoldPrint(a ...interface{}) {
	_ = Stderr.Print(BOLD, a...)
}

func EBoldPrintf(format string, a ...interface{}) {
	_ = Stderr.printf(BOLD, format, a...)
}

func EBoldPrintln(a ...interface{}) {
	_ = Stderr.Println(BOLD, a...)
}

func UnderlineString(format string, a ...interface{}) String {
	return colorString(UNDERLINE, format, a...)
}

func UnderlinePrint(a ...interface{}) {
	_ = Stdout.Print(UNDERLINE, a...)
}

func UnderlinePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(UNDERLINE, format, a...)
}

func UnderlinePrintln(a ...interface{}) {
	_ = Stdout.Println(UNDERLINE, a...)
}

func EUnderlinePrint(a ...interface{}) {
	_ = Stderr.Print(UNDERLINE, a...)
}

func EUnderlinePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(UNDERLINE, format, a...)
}

func EUnderlinePrintln(a ...interface{}) {
	_ = Stderr.Println(UNDERLINE, a...)
}

func ItalicString(format string, a ...interface{}) String {
	return colorString(ITALIC, format, a...)
}

func ItalicPrint(a ...interface{}) {
	_ = Stdout.Print(ITALIC, a...)
}

func ItalicPrintf(format string, a ...interface{}) {
	_ = Stdout.printf(ITALIC, format, a...)
}

func ItalicPrintln(a ...interface{}) {
	_ = Stdout.Println(ITALIC, a...)
}

func EItalicPrint(a ...interface{}) {
	_ = Stderr.Print(ITALIC, a...)
}

func EItalicPrintf(format string, a ...interface{}) {
	_ = Stderr.printf(ITALIC, format, a...)
}

func EItalicPrintln(a ...interface{}) {
	_ = Stderr.Println(ITALIC, a...)
}

func BoldUnderlineString(format string, a ...interface{}) String {
	return colorString(BOLDUNDERLINE, format, a...)
}

func BoldUnderlinePrint(a ...interface{}) {
	_ = Stdout.Print(BOLDUNDERLINE, a...)
}

func BoldUnderlinePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(BOLDUNDERLINE, format, a...)
}

func BoldUnderlinePrintln(a ...interface{}) {
	_ = Stdout.Println(BOLDUNDERLINE, a...)
}

func EBoldUnderlinePrint(a ...interface{}) {
	_ = Stderr.Print(BOLDUNDERLINE, a...)
}

func EBoldUnderlinePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(BOLDUNDERLINE, format, a...)
}

func EBoldUnderlinePrintln(a ...interface{}) {
	_ = Stderr.Println(BOLDUNDERLINE, a...)
}

func RedUnderlineString(format string, a ...interface{}) String {
	return colorString(REDUNDERLINE, format, a...)
}

func RedUnderlinePrint(a ...interface{}) {
	_ = Stdout.Print(REDUNDERLINE, a...)
}

func RedUnderlinePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(REDUNDERLINE, format, a...)
}

func RedUnderlinePrintln(a ...interface{}) {
	_ = Stdout.Println(REDUNDERLINE, a...)
}

func ERedUnderlinePrint(a ...interface{}) {
	_ = Stderr.Print(REDUNDERLINE, a...)
}

func ERedUnderlinePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(REDUNDERLINE, format, a...)
}

func ERedUnderlinePrintln(a ...interface{}) {
	_ = Stderr.Println(REDUNDERLINE, a...)
}

func GreenUnderlineString(format string, a ...interface{}) String {
	return colorString(GREENUNDERLINE, format, a...)
}

func GreenUnderlinePrint(a ...interface{}) {
	_ = Stdout.Print(GREENUNDERLINE, a...)
}

func GreenUnderlinePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(GREENUNDERLINE, format, a...)
}

func GreenUnderlinePrintln(a ...interface{}) {
	_ = Stdout.Println(GREENUNDERLINE, a...)
}

func EGreenUnderlinePrint(a ...interface{}) {
	_ = Stderr.Print(GREENUNDERLINE, a...)
}

func EGreenUnderlinePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(GREENUNDERLINE, format, a...)
}

func EGreenUnderlinePrintln(a ...interface{}) {
	_ = Stderr.Println(GREENUNDERLINE, a...)
}

func BlueUnderlineString(format string, a ...interface{}) String {
	return colorString(BLUEUNDERLINE, format, a...)
}

func BlueUnderlinePrint(a ...interface{}) {
	_ = Stdout.Print(BLUEUNDERLINE, a...)
}

func BlueUnderlinePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(BLUEUNDERLINE, format, a...)
}

func BlueUnderlinePrintln(a ...interface{}) {
	_ = Stdout.Println(BLUEUNDERLINE, a...)
}

func EBlueUnderlinePrint(a ...interface{}) {
	_ = Stderr.Print(BLUEUNDERLINE, a...)
}

func EBlueUnderlinePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(BLUEUNDERLINE, format, a...)
}

func EBlueUnderlinePrintln(a ...interface{}) {
	_ = Stderr.Println(BLUEUNDERLINE, a...)
}

func CyanUnderlineString(format string, a ...interface{}) String {
	return colorString(CYANUNDERLINE, format, a...)
}

func CyanUnderlinePrint(a ...interface{}) {
	_ = Stdout.Print(CYANUNDERLINE, a...)
}

func CyanUnderlinePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(CYANUNDERLINE, format, a...)
}

func CyanUnderlinePrintln(a ...interface{}) {
	_ = Stdout.Println(CYANUNDERLINE, a...)
}

func ECyanUnderlinePrint(a ...interface{}) {
	_ = Stderr.Print(CYANUNDERLINE, a...)
}

func ECyanUnderlinePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(CYANUNDERLINE, format, a...)
}

func ECyanUnderlinePrintln(a ...interface{}) {
	_ = Stderr.Println(CYANUNDERLINE, a...)
}

func YellowUnderlineString(format string, a ...interface{}) String {
	return colorString(YELLOWUNDERLINE, format, a...)
}

func YellowUnderlinePrint(a ...interface{}) {
	_ = Stdout.Print(YELLOWUNDERLINE, a...)
}

func YellowUnderlinePrintf(format string, a ...interface{}) {
	_ = Stdout.printf(YELLOWUNDERLINE, format, a...)
}

func YellowUnderlinePrintln(a ...interface{}) {
	_ = Stdout.Println(YELLOWUNDERLINE, a...)
}

func EYellowUnderlinePrint(a ...interface{}) {
	_ = Stderr.Print(YELLOWUNDERLINE, a...)
}

func EYellowUnderlinePrintf(format string, a ...interface{}) {
	_ = Stderr.printf(YELLOWUNDERLINE, format, a...)
}

func EYellowUnderlinePrintln(a ...interface{}) {
	_ = Stderr.Println(YELLOWUNDERLINE, a...)
}
